"""first

Revision ID: 5cfbc4b1ce48
Revises: e31beef93767
Create Date: 2025-04-29 12:12:46.498360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfbc4b1ce48'
down_revision = 'e31beef93767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=False, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.String(), nullable=False, comment='Зарплата от'))
    op.add_column('jobs', sa.Column('salary_to', sa.String(), nullable=False, comment='Зарплата до'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия'))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'))
    op.add_column('responses', sa.Column('message', sa.String(), nullable=False, comment='сообщение'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
